sudo: false
dist: trusty
language: rust

cache:
- cargo

before_cache:
- rm -r $TRAVIS_BUILD_DIR/target/debug

jobs:
  include:
  - os: linux
    rust: stable
  - os: linux
    rust: beta
  - os: linux
    rust: nightly

  # deploy
  - stage: publish
    os: linux
    rust: stable
    env:
    # CARGO_TOKEN
    - secure: "qHOydmz3Un/32JFlWEGYc4VzqKNBrOODOrVQxKO6u6NqTDo+4vGK7xLtct5rx58vF77BvSdfiR6RRcqIuYlWKNA/WbPCTolmy2cAkSztzjhpvmyF18LoM32gdaaRJ5+6Zay64/vG5LtE5QhIhFzmbJ6opBVv9PaQR1ptI/0Ss+gyvI7jw5WZAoUV4YD5ODTacdCAcoVohHHQcSxpMMVWQp7hFf8ZWwVVYQOZF44AZ3N9BHRc9MKr9XQ70E+TvHJjGRdwJIX6mNpWlI43JwkN2DeVA6cA/eWh91zLWkmkzNuYW63He02ueS9iTXvkoZnQysSMgB7TNNkP4TtlY2udvL7tO2UXt+6Wbh1kMESrtsvUSK9363Q/lrVSUKV3DZUFQC8CMh3Enn+W/2hyE/YDghcip+P7FHbrTf4TuWUzSWXA20xBMn/kkTWzX4gchTcrRKqW7RZHNZpOOplGvnW5JfGnRKC9CDx+kT+IGrKvnVsnRNqGI8bAm5SKgu6Nqr9TLxIQ6IKv/FAuQSjKh7l6STwNVPv5q3bji8zmEeSonKhSCbtSfHRepnY16mirM3Fw5f1beoDZR0qwsaIHnJz0RS0Mw7iuB0mt0bnpqgrl/agLmrjPrRQtPo01eqnli8ZU5cSpAND7B+ZWfqRFGdekyXsKJNAWycqAjOjg0qCjJEA="
    install: true
    script: true

    deploy:
    - provider: script
      script: 'cargo publish --verbose --token=$CARGO_TOKEN'
      on:
        tags: true
